# Generated by Django 3.2 on 2022-05-19 03:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3c460d60-f793-451b-88d2-24312760454e')),
        ),
    ]
