# Generated by Django 3.2 on 2022-05-19 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6822c5a8-31b0-4dbd-87b1-afd4601737bb')),
        ),
    ]
