# Generated by Django 3.2 on 2022-05-19 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fc3f4e4c-a9c3-4f06-922c-8e9cef87a10b')),
        ),
    ]
