# Generated by Django 3.2 on 2022-05-19 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.CharField(choices=[('L', 'Libro'), ('R', 'Revistas')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(blank=True, choices=[('D', 'Digital'), ('F', 'Libro fisico')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
